In [20]:
import nltk
# nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd
import numpy as np

In [21]:
gutenberg.fileids()

['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

In [22]:
for i in gutenberg.fileids():
    print(i)

austen-emma.txt
austen-persuasion.txt
austen-sense.txt
bible-kjv.txt
blake-poems.txt
bryant-stories.txt
burgess-busterbrown.txt
carroll-alice.txt
chesterton-ball.txt
chesterton-brown.txt
chesterton-thursday.txt
edgeworth-parents.txt
melville-moby_dick.txt
milton-paradise.txt
shakespeare-caesar.txt
shakespeare-hamlet.txt
shakespeare-macbeth.txt
whitman-leaves.txt

In [23]:
emma = gutenberg.raw('austen-emma.txt')

In [24]:
text = {}
for i in gutenberg.fileids():
    author = i.split("-")[0]
    if author not in text:
        text[author] = []
    text[author].append(gutenberg.raw(i))

In [39]:
authors = list(text.keys())
print(authors)

['austen', 'bible', 'blake', 'bryant', 'burgess', 'carroll', 'chesterton', 'edgeworth', 'melville', 'milton', 'shakespeare', 'whitman']

In [35]:
df = pd.DataFrame(list(text.items()),columns = ['author','text'])

In [44]:
df

         author                                               text
0        austen  [[Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHA...
1         bible  [[The King James Bible]\n\nThe Old Testament o...
2         blake  [[Poems by William Blake 1789]\n\n \nSONGS OF ...
3        bryant  [[Stories to Tell to Children by Sara Cone Bry...
4       burgess  [[The Adventures of Buster Bear by Thornton W....
5       carroll  [[Alice's Adventures in Wonderland by Lewis Ca...
6    chesterton  [[The Ball and The Cross by G.K. Chesterton 19...
7     edgeworth  [[The Parent's Assistant, by Maria Edgeworth]\...
8      melville  [[Moby Dick by Herman Melville 1851]\r\n\r\n\r...
9        milton  [[Paradise Lost by John Milton 1667] \n \n \nB...
10  shakespeare  [[The Tragedie of Julius Caesar by William Sha...
11      whitman  [[Leaves of Grass by Walt Whitman 1855]\n\n\nC...

In [51]:
df2 = pd.DataFrame()

author = []
text = []
label = []

for i in df.iterrows():
    for j in range(len(i[1]['text'])):
        author.append(i[1]['author'])
        text.append(i[1]['text'][j])
        label.append(authors.index(i[1]['author']))
        
df2 = pd.DataFrame({'author': author, 'text': text, 'label': label})
df2

         author                                               text  label
0        austen  [Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAP...      0
1        austen  [Persuasion by Jane Austen 1818]\n\n\nChapter ...      0
2        austen  [Sense and Sensibility by Jane Austen 1811]\n\...      0
3         bible  [The King James Bible]\n\nThe Old Testament of...      1
4         blake  [Poems by William Blake 1789]\n\n \nSONGS OF I...      2
5        bryant  [Stories to Tell to Children by Sara Cone Brya...      3
6       burgess  [The Adventures of Buster Bear by Thornton W. ...      4
7       carroll  [Alice's Adventures in Wonderland by Lewis Car...      5
8    chesterton  [The Ball and The Cross by G.K. Chesterton 190...      6
9    chesterton  [The Wisdom of Father Brown by G. K. Chesterto...      6
10   chesterton  [The Man Who Was Thursday by G. K. Chesterton ...      6
11    edgeworth  [The Parent's Assistant, by Maria Edgeworth]\r...      7
12     melville  [Moby Dick by Herman Melville 1851]\r\n\r\n\r\...      8
13       milton  [Paradise Lost by John Milton 1667] \n \n \nBo...      9
14  shakespeare  [The Tragedie of Julius Caesar by William Shak...     10
15  shakespeare  [The Tragedie of Hamlet by William Shakespeare...     10
16  shakespeare  [The Tragedie of Macbeth by William Shakespear...     10
17      whitman  [Leaves of Grass by Walt Whitman 1855]\n\n\nCo...     11